#ifndef _H_ERR_
#define _H_ERR_

#include <stdio.h>

typedef enum {
    SUCCESS = 0,
    INVALID_LABEL_NAME = 1,
    LINE_TOO_LONG = 2,
    INVALID_FILE_END = 3,
    FILE_OPEN_ERROR = 4,
    ERR_DUPLICATE_SYMBOL = 5,
    ERR_INVALID_SYNTAX_ENTRY_DECLERATION = 6,
    ERR_ENTRY_SYM_NOT_FOUND = 7,
    ERR_INVALID_LABEL = 8,
    ERR_INVALID_COMMAND_NAME = 9,
    ERR_INVALID_COMMAND_FORMAT = 10,
    ERR_UNTERMINATED_STRING_ARG = 11,
    ERR_INVALID_CODE_INSTRUCTION = 12,
    ERR_INVALID_REGISTER = 13,
    ERR_INVALID_NUMBER_TOKEN = 14,
    ERR_INVALID_NUMBER_SIZE = 15,
    ERR_INVALID_INSTRUCTION_TYPE = 16,
    ERR_INVALID_DATA_INSTRUCTION = 17,
    ERR_EOF = 18,
    ERR_UNKNOWN_LABEL_REFERENCED = 19,
    ERR_INVALID_EXTERNAL_LABEL_REFERENCE = 20,
    ERR_LABEL_TOO_FAR = 21,
    ERR_MEMORY_INVALID_STATE = 22,
    ERR_OUT_OF_MEMEORY = 23,
    ERR_FILENAME_TOO_LONG = 24,
    ERR_CREATING_OUTPUT_FILE = 25,
    ERR_SYMBOL_CANNOT_BE_ENTRY_AND_EXTERN = 26,
    ERR_INVALID_SYNTAX_EXTERN_DECLERATION = 27,
    ERR_ASCIZ_WITHOUT_QUOTES = 28
} ErrorType;

void printErr(ErrorType err);

#endif
