#ifndef _H_ERR_
#define _H_ERR_

#include <stdio.h>

typedef enum {
    SUCCESS = 0,
    LINE_TOO_LONG = 1,
    FILE_OPEN_ERROR = 2,
    ERR_DUPLICATE_SYMBOL = 3,
    ERR_INVALID_SYNTAX_ENTRY_DECLERATION = 4,
    ERR_ENTRY_SYM_NOT_FOUND = 5,
    ERR_INVALID_COMMAND_NAME = 6,
    ERR_INVALID_COMMAND_FORMAT = 7,
    ERR_INVALID_CODE_INSTRUCTION = 8,
    ERR_INVALID_REGISTER = 9,
    ERR_INVALID_NUMBER_TOKEN = 10,
    ERR_INVALID_NUMBER_SIZE = 11,
    ERR_INVALID_INSTRUCTION_TYPE = 12,
    ERR_INVALID_DATA_INSTRUCTION = 13,
    ERR_EOF = 14,
    ERR_UNKNOWN_LABEL_REFERENCED = 15,
    ERR_INVALID_EXTERNAL_LABEL_REFERENCE = 20,
    ERR_LABEL_TOO_FAR = 21,
    ERR_MEMORY_INVALID_STATE = 22,
    ERR_OUT_OF_MEMEORY = 23,
    ERR_FILENAME_TOO_LONG = 24,
    ERR_CREATING_OUTPUT_FILE = 25,
    ERR_SYMBOL_CANNOT_BE_ENTRY_AND_EXTERN = 26,
    ERR_INVALID_SYNTAX_EXTERN_DECLERATION = 27,
    ERR_ASCIZ_WITHOUT_QUOTES = 28,
    ERR_LABEL_WITH_BAD_CHARACTERS = 29,
    ERR_LABEL_MUST_START_WITH_LETTERS = 30,
    ERR_LABEL_TOO_LONG = 31,
    ERR_INVALID_LABEL_USING_RESERVED_NAME = 32

} ErrorType;

void printErr(ErrorType err);

#endif
